site_name: Prunelle D. Treuil
docs_dir: 'docs'

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/tree-outline
  favicon: assets/favicon.ico
  font: false
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
- Home: index.md
- Projects: 
    - Internship: projects/internship.md
    - Msc NLP: projects/tal.md
- CV (PDF): ptreuilCV.pdf

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
# https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage
  - attr_list
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/ go to the right §
  - def_list
# https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - footnotes
# https://squidfunk.github.io/mkdocs-material/reference/footnotes/#adding-footnote-references
# https://squidfunk.github.io/mkdocs-material/reference/footnotes/#adding-footnote-content
  - pymdownx.betterem
# allow **bold** and _italic_
  - pymdownx.highlight:
      use_pygments: true
# https://facelessuser.github.io/pymdown-extensions/extensions/highlight/

  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: macros.tex
# pip install markdown-katex
# https://github.com/mbarkhau/markdown-katex?tab=readme-ov-file

plugins:
  - privacy
  - search

  - i18n:
      reconfigure_material: true
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ptreuil/
    - icon: fontawesome/brands/github
      link: https://github.com/ptreuil