site_name: Prunelle D. Treuil

theme:
  name: simple-blog
  custom_dir: overrides
  colors:
    title: green
  site_name_style: italic
  title_style: underline
  logo: logo.png
  favicon: favicon.ico

nav:
- Home: index.md
- Projects: 
    - Internship: projects/internship.md
    - Msc NLP: projects/tal.md
- CV (PDF): ptreuilCV.pdf

markdown_extensions:
  - toc:
      baselevel: "1"
      toc_depth: "3"
