site_name: Prunelle D. Treuil
docs_dir: '../../docs/fr'                           # Where to find the English markdown files
site_dir: '../../generated/fr'                      # Where to put the English HTML files

theme:
  #name: simple-blog
  name: material
  custom_dir: ../../overrides
  #colors:
  #  title: green
  #site_name_style: italic
  #title_style: underline
  logo: logo.png
  favicon: favicon.ico
  language: fr

nav:
- Home: index.md
- Projects: 
    - Internship: projects/internship.md
    - Msc NLP: projects/tal.md
- CV (PDF): ptreuilCV.pdf

markdown_extensions:
  - toc:
      baselevel: "1"
      toc_depth: "3"

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Français
      link: /fr/
      lang: fr

plugins:
  - search:                                         
      lang: en   